services:
    Vairogs\Twig\Helper\Date\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Email\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\File\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Generator\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Gravatar\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Http\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Identification\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Iter\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Json\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Php\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Sort\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Text\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Translit\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Uri\Extension:
        public: false
        tags:
            -
                name: twig.extension

    Vairogs\Twig\Helper\Util\Extension:
        public: false
        tags:
            -
                name: twig.extension
